DROP TABLE IF EXISTS `UC_COMPANY_INFO`;
CREATE TABLE `UC_COMPANY_INFO` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_INFO_ID` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户信息表主键',
  `COMPANY_NAME` VARCHAR(120) CHARACTER SET utf8 NOT NULL COMMENT '企业名称',
  `COMPANY_SHORT_NAME` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '企业简称',
  `COMPANY_TYPE` TINYINT(2) UNSIGNED DEFAULT NULL COMMENT '企业类型',
  `MCC` VARCHAR(120) CHARACTER SET utf8 DEFAULT NULL COMMENT '行业编号',
  `POST` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮编',
  `FAX` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '传真',
  `PROVINCE` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '省份',
  `CITY` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '地市',
  `CONTACTS` VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '联系人',
  `CONTACTS_INFO` VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '联系方式',
  `REGIST_FINACNCE` VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '注册资金',
  `MEMBERS` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '员工数',
  `ADDRESS` VARCHAR(120) CHARACTER SET utf8 DEFAULT NULL COMMENT '地址',
  `WEBSITE` VARCHAR(120) CHARACTER SET utf8 DEFAULT NULL COMMENT '网址',
  `BUSLINCE` VARCHAR(60) CHARACTER SET utf8 NOT NULL COMMENT '营业执照号',
  `BUSLINCE_EXPIRE_TIME` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '营业执照号过期时间',
  `ACUNT_OPN_LINCE` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '开户许可证',
  `TAXREG_CARD1` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '税务登记证1',
  `TAXREG_CARD2` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '税务登记证2',
  `ORGAN_CERTIFICATE` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '住址机构代码证',
  `CORPORATE_NAME` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '法人姓名',
  `CORPORATE_IDENTITY` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '法人身份证',
  `CORPORATE_TEL` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '法人电话',
  `CORPORATE_MAIL` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '法人邮箱',
  `BUS_PLACE_CTF` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '经营场所实地认证',
  `LOAN_CARD` VARCHAR(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '贷款卡',
  `OTHERINFO1` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用1',
  `OTHERINFO2` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用2',
  `OTHERINFO3` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用3',
  `REMARK` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='企业信息表';


/*Table structure for table `UC_PERSON_INFO` */

DROP TABLE IF EXISTS `UC_PERSON_INFO`;

CREATE TABLE `UC_PERSON_INFO` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `USER_INFO_ID` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户信息表主键',
  `USER_CNAME` VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户中文名字',
  `USER_ENAME` VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户英文名字',
  `USER_TYPE` TINYINT(3) UNSIGNED DEFAULT '0' COMMENT '用户类型',
  `GENDER` CHAR(1) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户性别',
  `BIRTHDAY` DATE DEFAULT NULL COMMENT '用户生日',
  `ID_NUMBER` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '身份证号',
  `ID_NUMBER_EXPIRE_TIME` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证过期时间',
  `ID_NUMBER_ADDRESS` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证地址',
  `ETHNIC` VARCHAR(20) COLLATE utf8_bin DEFAULT NULL COMMENT '民族',
  `POLICE_STATION` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证签发机关',
  `ADDRESS` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户地址',
  `MOBILE_PHONE` VARCHAR(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '移动电话',
  `FIXED_PHONE` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '固定电话',
  `EMAIL` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮箱',
  `HANDLER_FAX` VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '传真号',
  `NATIONAL` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '国家',
  `PROVINCE` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '省',
  `CITY` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '市',
  `DISTRICT` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '区',
  `ZIP_CODE` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮政编码',
  `EDUCATION` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '学历',
  `POLITICAL_STATUS` VARCHAR(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '政治面貌',
  `INDUSTRY` VARCHAR(8) CHARACTER SET utf8 DEFAULT NULL COMMENT '所属行业',
  `COMPANY_NAME` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '公司名称',
  `COMPANY_ATTRIBUTE` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '公司性质',
  `COMPANY_PHONE` VARCHAR(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '公司电话',
  `JOB_ATTRIBUTE` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '工作性质',
  `OCCUPATION` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '职位',
  `MARRIAGE` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '是否结婚',
  `FAMILY_SIZE` TINYINT(2) UNSIGNED DEFAULT '0' COMMENT '家庭人口数量',
  `PERSON_INCOME` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '个人收入',
  `FAMILY_INCOME` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '家庭收入',
  `COME_FROM` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户来源',
  `QQ_NUMBER` VARCHAR(16) CHARACTER SET utf8 DEFAULT NULL COMMENT 'QQ号',
  `WECHAT_NUMBER` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '微信号',
  `WEBO_NUMBER` VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '微博号',
  `ISAUTHOR` TINYINT(2) UNSIGNED DEFAULT NULL COMMENT '实名验证类型',
  `OTHERINFO1` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用1',
  `OTHERINFO2` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用2',
  `OTHERINFO3` VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '备用3',
  `REMARK` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户备注',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=153 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户信息表';



DROP TABLE IF EXISTS `UC_USER_INFO`;

CREATE TABLE `UC_USER_INFO` (
  `USER_INFO_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户信息主键',
  `USER_ID` VARCHAR(32) NOT NULL COMMENT '用户ID',
  `USER_CODE` VARCHAR(32) DEFAULT NULL COMMENT '用户编码',
  `CAAS_USER_CODE` VARCHAR(32) DEFAULT NULL COMMENT 'caas用户编码',
  `USER_TYPE` TINYINT(4) UNSIGNED DEFAULT NULL COMMENT '用户类型  1商户  2个人 3微信 4支付宝 5其他',
  `STATUS` TINYINT(4) UNSIGNED DEFAULT NULL COMMENT '用户状态  1正常 2初始化 3caas失败 0禁用  9删除',
  `VERSION` INT(11) UNSIGNED DEFAULT '1' COMMENT '版本',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `APP_CODE` VARCHAR(32) DEFAULT NULL COMMENT '应用code',
  `ORG_CODE` VARCHAR(32) NOT NULL COMMENT '机构ID',
  `ID_CARD_NUMBER` VARCHAR(32) DEFAULT NULL COMMENT '身份证号/营业执照号',
  `IS_IDENTIFY` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否实名制1已实名制0未实名制',
  PRIMARY KEY (`USER_INFO_ID`),
  UNIQUE KEY `UK_UC_USER_INFO01` (`USER_ID`,`ORG_CODE`)
) ENGINE=INNODB AUTO_INCREMENT=225 DEFAULT CHARSET=utf8;


/*Table structure for table `UC_USER_LOGIN` */

DROP TABLE IF EXISTS `UC_USER_LOGIN`;


CREATE TABLE `UC_USER_LOGIN` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '登陆ID',
  `USER_INFO_ID` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户编码(个人或企业)',
  `PWD_SALT` VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '密码盐值',
  `PWD_MD` VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '密码',
  `USER_TYPE` TINYINT(4) UNSIGNED NOT NULL COMMENT '用户类型 1企业  2个人',
  `LOGIN_NAME` VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '登陆名(手机)',
  `ORG_CODE` VARCHAR(12) COLLATE utf8_bin NOT NULL COMMENT '机构号',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_UC_USER_LOGIN01` (`LOGIN_NAME`,`ORG_CODE`)
) ENGINE=INNODB AUTO_INCREMENT=211 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户登陆信息表';

CREATE TABLE `UC_SYSTEM_CONFIG` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CONFIG_KEY` VARCHAR(100) NOT NULL COMMENT '配置键',
  `CONFIG_VALUE` VARCHAR(200) NOT NULL COMMENT '配置值',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户中心系统配置表';
INSERT INTO `UC_SYSTEM_CONFIG` (`ID`, `CONFIG_KEY`, `CONFIG_VALUE`) VALUES('1','almond_errorpwd_expire_time','600');
